version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8010:8010"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"